# Generated by Django 2.2.7 on 2019-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='simage',
            field=models.CharField(default='dummy.jpg', max_length=255),
        ),
    ]
