# Generated by Django 2.2.6 on 2019-10-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
