# Generated by Django 2.2.7 on 2019-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.FileField(default='', upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default='draft', max_length=10),
        ),
    ]
