# Generated by Django 2.2.7 on 2019-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191109_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_post',
            new_name='thumbnail',
        ),
    ]
