# Generated by Django 2.2.7 on 2019-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191109_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='nophoto.png', upload_to='thumbnail/'),
        ),
    ]
